; EnemyOne.inc : それぞれのエネミー
;


; マクロの定義
;

; スケルトン

; 外部関数宣言
;

    .globl  _EnemySlime
    .globl  _EnemyCyclops
    .globl  _EnemyXorn
    .globl  _EnemyLizard
    .globl  _EnemySkelton
    .globl  _EnemyPhantom
    .globl  _EnemyTroll
    .globl  _EnemyDaemon
    .globl  _EnemyGremlin

; 外部変数宣言
;

    .globl  _enemySlimeDefault
    .globl  _enemyDaemonDefault
    .globl  _enemyXornDefault
    .globl  _enemyLizardDefault
    .globl  _enemySkeltonDefault
    .globl  _enemyPhantomDefault
    .globl  _enemyCyclopsDefault
    .globl  _enemyTrollDefault
    .globl  _enemyGremlinDefault

