; Item.inc : アイテム
;


; マクロの定義
;

; アイテム
ITEM_NULL                       =   0x00
ITEM_CRYSTAL_RED                =   0x01
ITEM_CRYSTAL_GREEN              =   0x02
ITEM_CRYSTAL_BLUE               =   0x03
ITEM_CRYSTAL_YELLOW             =   0x04
ITEM_CRYSTAL_WHITE              =   0x05
ITEM_KEY                        =   0x06
ITEM_RING                       =   0x07
ITEM_ROD                        =   0x08
ITEM_NECKLACE                   =   0x09
ITEM_CANDLE                     =   0x0a
ITEM_LENGTH                     =   0x0b

; 外部関数宣言
;

; 外部変数宣言
;
